import java.util.Scanner;

public class ExceptionFirst {
    public static void main(String[] args) {
        // int num1 = 2;
        // int num2 = 2;
        // int result = 0;
        // int value[] = { 2, 4, 5, 3, 7 };
        // try {
        // result = num1 / num2;
        // System.out.println(value[5]);
        // } catch (ArithmeticException obj) {
        // System.out.println("Something Went wrong" + obj);
        // } catch (ArrayIndexOutOfBoundsException e) {
        // System.out.println("Stay in your limit");
        // System.out.println(value[value.length - 1]);

        // }
        // System.out.println(result);
        // System.out.println("Hello");

        // *******************************Finally block****************

        int num = 0;
        Scanner sc = new Scanner(System.in);
        num = sc.nextInt();
        System.out.println(num);
    }
}
